# version: '3.8' # Obsolete in newer Docker Compose versions

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: latinad_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - latinad_network
    depends_on:
      - db
      - redis
    environment:
      - APP_ENV=local
      - APP_DEBUG=true

  web:
    image: nginx:alpine
    container_name: latinad_web
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    networks:
      - latinad_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: latinad_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: latinad_db
      MYSQL_USER: latinad_user
      MYSQL_PASSWORD: latinad_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - latinad_network
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:alpine
    container_name: latinad_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - latinad_network
    command: redis-server --appendonly yes

  mailhog:
    image: mailhog/mailhog:latest
    container_name: latinad_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - latinad_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: latinad_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: latinad_user
      PMA_PASSWORD: latinad_password
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - latinad_network
    depends_on:
      - db

networks:
  latinad_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
